version: "3.0"
services:
  nginx-php-fpm:
    image: richarvey/nginx-php-fpm:latest
    container_name: nginx-php
    restart: always
    ports:
      - 8080:80
      - 443:443
      - 9000:9000
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./www:/var/www
    # environment:
    #   SSH_KEY: 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAwrMUo8v2/zD9Kfg5MSzeAWvx2xiQPpT1vz90y3MIyUYn5lYf4EgcmcseSEJ/qmKWcWOj30geGrKOq2X110xLCNTVVJ7Xq7pHRnjIshxqcQGHKHyAE20ngVcQlmUoir5AY/4seqxfYH6abbWtg2qEo0CelagSkH08EL0zYDTJBzyRaf8O/xgzAhGBsXk2pVTFP1RcpDFZSUfAnwNpL+kgjv3k9UZJOD1BIzmAxZdfj9d3btjZymIGOyyxyD7VTxY1sKOKKeWf2DQjgw0uJJ36VlUB06OuXehbeRGggnBA7XKHx1MgqXMTJ4cMsUZHKAoLiaZTtJaVvwsyPkxLxMW85Q== zhangxin@uuke.com.cn'
    #   GIT_REPO: 'github.com/zxjhansin/tp5.git'
    #   GIT_EMAIL: 'zhangxin@uuke.com.cn'
    #   GIT_USERNAME: 'zhangxin'
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
  proxy:
    image: dockerflow/docker-flow-proxy
    ports:
      - "8000:80"
      - "8443:443"
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=listener
      - MODE=swarm
      - TIMEOUT_CLIENT=40
      - TIMEOUT_SERVER=40
      - DEBUG=true
      - DEBUG_ERRORS_ONLY=true
    deploy:
      placement:
        constraints: [node.role == manager]

  listener:
    image: vfarcic/docker-flow-swarm-listener:17.11.11-22
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  proxy:
    external: true
