#-------------------------------------------------------------------------------
# mdc/proxy
# 20171121
#

FROM vfarcic/docker-flow-proxy:17.10.14-45
MAINTAINER Jim Wang <jimw@invosas.com>

ADD certs /certs