version: "3.0"
services:
  proxy:
    image: dockerflow/docker-flow-proxy
    ports:
      - $HTTP:80
      - $HTTPS:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=listener
      - MODE=swarm
      - TIMEOUT_CLIENT=40
      - TIMEOUT_SERVER=40
      - DEBUG=true
      - DEBUG_ERRORS_ONLY=
    volumes:
      - ./haproxy.cfg:/cfg/haproxy.cfg
    deploy:
      placement:
        constraints: [node.role == manager]
  listener:
    image: vfarcic/docker-flow-swarm-listener:17.11.11-22
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]
networks:
  proxy:
    external: true