#!/bin/bash

#-------------------------------------------------------------------------------
# Project config

export PRJ=proxy
export PROXY=fe
export TIMEOUT=40
export HTTP=8000
export HTTPS=443
export SCALE=1

function install {
	PROXY=`docker network inspect proxy`
	if [ "$PROXY" == "[]" ]; then
		docker network create -d overlay proxy
	fi
	restart 10
}

function _post_restart {
	docker service scale proxy_proxy=$SCALE
}

#-------------------------------------------------------------------------------
# Common Service 

if [ -f /srv/service ]; then
	source /srv/service
fi
