version: "3.0"
services:
  easyswoole:
    image: easyswoole/easyswoole3
    container_name: easyswoole
    ports:
      - 9501:9501
    volumes:
      - /www/easyswoole:/easyswoole
  gitLab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    ports:
      - 2222:22
      - 2288:80
      - 2443:443
    volumes:
      - /var/gitlab/config:/etc/gitlab
      - /var/gitlab/repo:/var/opt/gitlab
      - /var/gitlab/log:/var/log/gitlab
  showDoc:
    image: star7th/showdoc
    container_name: showDoc
    restart: always
    ports:
      - 4999:80
    volumes:
      - /var/showdoc_data/html:/var/www/html  
  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins
    restart: always
    ports:
      - 8888:8080
      - 50000:50000
    volumes:
      - /var/jenkins_home:/var/jenkins_home
  vue:
    build:
      context: ./vue
    container_name: vue
    ports:
      - 8080:80
    volumes:
      - ../vue:/usr/share/nginx/html/
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./www:/var/www
    depends_on:
      - php-fpm
      - mysql

  php-fpm:
    build:
      context: ./php-fpm
    container_name: php
    ports:
      - 9000:9000
    volumes:
      - ./php-fpm/conf-7.2/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/conf-7.2/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php-fpm/conf-7.2/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./www:/var/www
  mysql:
    build:
      context: ./mysql
      # args:
        # - MYSQL_VERSION=${MYSQL_VERSION}
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  mongo:
    build:
      context: ./mongo
      # args:
        # - MONGO_VERSION=${MONGO_VERSION}
    container_name: mysql
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
  redis:
    build:
      context: ./redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    restart: always
  memcached:
    build:
      context: ./memcached
    container_name: memcached
    ports:
      - 11211:11211