#-------------------------------------------------------------------------------
# moca/user
# 20180706
#

FROM jhansin/nginx-php-tp6:latest
MAINTAINER Jhansin <jhansin@163.com>

ADD ./src/user /usr/share/nginx/html/public/tp/app/user